# Site settings
title: Conal
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cms5109.github.io" # the base hostname & protocol for your site
twitter_username: cms5109
github_username:  cms5109

# Build settings
markdown: kramdown

#Permalink settings
permalink: /posts/:year/:month/:day/:title/

#Skills for progress bars
skills:
 - Lean: 85
 - Grammar: 84
 - ScrumMastering: 83 
 - "Product Management": 80
 - "Ruby on Rails": 79
 - HTML:  72
 - SQL: 69
 - Javascript:  66
 - DevOps: 50
 - Cooking: 45
 - Design: 10
